### ISSUE TITLE
Mdi.Blank is not available

### ISSUE THREAD

**Issue by goyney** [TeamWertarbyte/mdi-material-ui#10]
`Mdi.Blank` is unavailable in this package. Please include it. :)

**Comment by leMaik** [comment]
That's because there is no `Blank` icon, at least I can't find one at https://materialdesignicons.com/

**Comment by goyney** [comment]
Blank is defined in the default Material Design Icons webfont here: https://github.com/Templarian/MaterialDesign-Webfont/blob/874a47b4e3ebf4bed58a88b2c01108c9dd5993d6/scss/_icons.scss#L7

It is a visibility hidden icon that maintains the same square dimensions as every other icon in the library and is used heavily in menu that have optional icons.

**Comment by leMaik** [comment]
Ah, now I get it… So it's a non-icon icon? Why would you need that?

**Comment by goyney** [comment]
"It is a visibility hidden icon that maintains the same square dimensions as every other icon in the library and is used heavily in menu that have optional icons."

For example, the Google Docs menus:
![screen shot 2018-05-13 at 12 50 43 pm](https://user-images.githubusercontent.com/1015040/39969606-597f1890-56ac-11e8-963e-5ef63dcdd9f1.png)

It maintains the same dimensions of every other icon, no matter the circumstances. It is also much easier to do something like:

```
import * as Mdi from 'mdi-material-ui';
const icon = React.createElement(Mdi[item.icon || 'Blank']);
```

**Comment by leMaik** [comment]
Material-UI's `SvgIcon` always has a size of 24x24 pixels. What you want to do can already be done with `<SvgIcon />`.

BTW You really, really shouldn't do what you showed in your example. That will result in all 2000+ icons being put into your bundle. :warning:
