### ISSUE TITLE
Update to use @material-ui/core

### ISSUE THREAD

**Issue by olee** [TeamWertarbyte/mdi-material-ui#11]
As of today `material-ui@next` moved to `@material-ui/core`, think you could make a quick update with the fixed dependency?

**Comment by leMaik** [comment]
Wow, that was quick. :smile:

**Comment by olee** [comment]
Will you publish a new version on npm then?
Can't wait to update my code (actually pretty much done and just the icons are missing 😅)

**Comment by leMaik** [comment]
@olee Same here :sweat_smile: v5.0.0 is up on npm now :package:
