### ISSUE TITLE
Update to 5.0.0 can no longer build

### ISSUE THREAD

**Issue by goyney** [TeamWertarbyte/mdi-material-ui#13]
Updating to 5.0.0 completely breaks our build system.

```
Server running at http://localhost:3000
🚨  /projectname/node_modules/mdi-material-ui/AccessPoint.js:11:23: Cannot resolve dependency '@mat   9 | var _react2 = _interopRequireDefault(_react);
  10 |
> 11 | var _SvgIcon = require('@material-ui/core/SvgIcon');
     |                        ^
  12 |
  13 | var _SvgIcon2 = _interopRequireDefault(_SvgIcon);
  14 |
```

Parcel 1.8.1
Yarn 1.6.0
Node 10.1.0
macOS

**Comment by leMaik** [comment]
It's a major release, because it breaks stuff. No need to update, there are no new icons (and I'll continue to add new icons in v4 as soon as they get released for the next few months).

v5.0.0 adds support for Material-UI 1.0.0, which changed the package from `material-ui` to `@material-ui/core`.

**Comment by goyney** [comment]
Not having an upgrade path is not a valid answer. There is no reason an icon libraries major release should blow up a dev pipeline over a dependency.
