### ISSUE TITLE
muiName is not passed through components

### ISSUE THREAD

**Issue by dantman** [TeamWertarbyte/mdi-material-ui#14]
Material UI recommends making sure to include the `muiName` [when you wrap components](https://material-ui.com/guides/composition/#wrapping-components).

This library's icons should probably set `.muiName = 'SvgIcon';` on exported icons. The icons in `@material-ui/icons` do this.

*mdi-material-ui:* 5.0.0

**Comment by leMaik** [comment]
Fixed in v4.1.1 (for legacy material-ui) and v5.1.1 (for material-ui ^1.0.0)
