### ISSUE TITLE
package size issue

### ISSUE THREAD

**Issue by soroushm** [TeamWertarbyte/mdi-material-ui#15]
Hello Dear Friend,

this package is over 2mb is very heavy for production 

<img width="459" alt="screen shot 2018-06-18 at 7 44 58 pm" src="https://user-images.githubusercontent.com/1031663/41545341-35e28c96-7330-11e8-826f-837d04275d52.png">

Please decrease package size

BR,

**Comment by leMaik** [comment]
How should I reduce it, am I suppose to remove all the icons _you_ don't need? :wink: 

The package size doesn't matter at all. What matters is the _resulting_ size of your app and that size will be as small as possible because you can import only the icons you need.
