### ISSUE TITLE
ChevronTripleRight icon

### ISSUE THREAD

**Issue by YuriGor** [TeamWertarbyte/mdi-material-ui#20]
Hi! 
This ››› icon looks so obviously useful, so I am wondering why it was added only [10 days ago](https://github.com/Templarian/MaterialDesign/commit/b62fb521cd13d034016a980f3f26596f27460faf)
When may I expect it will appear in mdi-mui?

**Comment by leMaik** [comment]
Thanks for the reminder! :smile: I just published [v5.10.0](https://github.com/TeamWertarbyte/mdi-material-ui/releases/tag/v5.10.0) (for @material-ui/core) and [v4.10.0](https://github.com/TeamWertarbyte/mdi-material-ui/releases/tag/v4.10.0) (for material-ui 0.x), featuring the latest v3.5.95 of Material Design Icons. :package: 

I checked and ChevronTripleRight is included, too. :+1:
