### ISSUE TITLE
supports @material-ui 4.0.0

### ISSUE THREAD

**Issue by minhna** [TeamWertarbyte/mdi-material-ui#22]
@material-ui version 4 is released. Could you please make an update?
Thank you.

**Comment by leMaik** [comment]
It _should_ work. I'll publish a new release with the updated peer dependency shortly.

**Comment by minhna** [comment]
thank you very much

**Comment by marcberchtold** [comment]
Would you also use React.forwardRef to create the icon components? Because this is required in some components in material-ui (V4). Described here: https://material-ui.com/guides/composition/#caveat-with-refs

**Comment by leMaik** [comment]
@minhna Just [released v6.0.0](https://github.com/TeamWertarbyte/mdi-material-ui/releases/tag/v6.0.0) for Material-UI v1, v3 and v4. It requires React 16.8 or later (hence the major bump). Here's a compatibility table. I'll update all three major versions for the foreseeable future.

| Material-UI | React | mdi-material-ui |
|---|---|---|
|0.x|_any_|^4.0.0|
|^1.0.0|_any_|^5.0.0|
|^3.0.0|_any_|^5.0.0|
|^4.0.0|^16.8.0|^6.0.0|

@marcberchtold Great idea! :+1: I updated the component to behave like Material UI's icons, it now uses `React.memo` and `React.forwardRef`.
