### ISSUE TITLE
FileSettingsVariant icon not found

### ISSUE THREAD

**Issue by elitan** [TeamWertarbyte/mdi-material-ui#23]
`import FileSettingsVariant from 'mdi-material-ui/FileSettingsVariant';`

```
./src/Components/xxxxx.js
Module not found: Can't resolve 'mdi-material-ui/FileSettingsVariant' in
```

Trying to import this link:
https://materialdesignicons.com/icon/file-settings-variant

**Comment by leMaik** [comment]
Are you using the latest version of mdi-material-ui?

**Comment by leMaik** [comment]
Somehow, this icon isn't included in `@mdi/js` v3.9.97 :scream:

**Comment by leMaik** [comment]
That icon was [only added 4 days ago](https://github.com/Templarian/MaterialDesign/issues/270#issuecomment-519748402) and thus isn't released in Material Design Icons yet. You'll have to wait until they release the icon and we update this package in order to use it via mdi-material-ui.

**Comment by elitan** [comment]
Ah, did not know that. Thanks for the info! :)

**Comment by leMaik** [comment]
Hey @elitan, just wanted to let you know that a new mdi version was published and mdi-material-ui was updated; the new version should include the FileSettingsVariant icon. :+1:

**Comment by elitan** [comment]
Perfect. Thank you very much.
