### ISSUE TITLE
Failed to process License file after update to 6.4.0

### ISSUE THREAD

**Issue by JonathasNascimento** [TeamWertarbyte/mdi-material-ui#24]
After update to last version this error is thrown broken the app:

```
Uncaught .\node_modules\mdi-material-ui\License:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) {         DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
                                                                                                                                                                      ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at createScript (vm.js:265:10)
    at Object.runInThisContext (vm.js:313:10)
    at Module._compile (internal/modules/cjs/loader.js:712:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (.\node_modules\mdi-material-ui\index.js:29335:39)

```

**Comment by leMaik** [comment]
Uhm… This looks like it's importing our license file.

**Comment by leMaik** [comment]
Somehow, your webpack environment seems to import `.md` files. Could you change the priority or something like that? It should use the `License.js` instead.

**Comment by JonathasNascimento** [comment]
Yes, it looks like a conflict with` License.js` and `LICENSE` file on import process. I remove `LICENSE` and it works well. If I change `LICENSE` to `LICENSE.md` it works too

I check my webpack config and has no entries to `.md` and the value `.js` is the most priority.

Maybe by default the file with no extension has more priority, but I don't know.

**Comment by LesterLyu** [comment]
The previous version didnot import LICENSE, which works fine.

**Comment by wesleyguirra** [comment]
having the same error here, it's seems that the LICENSE file is imported instead of License.js

**Comment by leMaik** [comment]
@JonathasNascimento That sounds like a great way to fix the issue. 👍 I'll release updates tomorrow.

**Comment by leMaik** [comment]
Turns out that this issue was only reproducible on systems where file names are insensitive, e.g. Windows. Anyway, it's fixed.
