### ISSUE TITLE
Update MDI

### ISSUE THREAD

**Issue by dantman** [TeamWertarbyte/mdi-material-ui#25]
MessageTextClock seems to be missing so I presume this library needs to be regenerated/updated for the new version.

Related, is this still the preferred method to use MDI with Material UI? The MDI website is directing people to the `@mdi/js` and `@mdi/react` packages. However I prefer this library's method of making the icons into importable components.

**Comment by leMaik** [comment]
I updated yesterday, so it should be up to date. Somehow, the MDI website also shows icons that aren't released yet.

Regarding the second question: I don't know if this is the _preferred_ method; it's at least the _simplest_ method (in my opinion) and I prefer it too. :sunglasses: I asked them and even created a PR that adds this library to their website and there was zero interest in supporting this library. One of the arguments was that this version contains too many files. Well, it's 2019 and computers don't have problems with thousands of files anymore, but hey... :man_shrugging:

**Comment by dantman** [comment]
That's a strange response of them.

Side topic, I notice now it looks like mdi-material-ui works by passing the svg path string to a createIcon function, rather than doing any static compilation with it. And it looks like `@mdi/js` exports the path strings.

Have you considered using `@mdi/js` instead of the inlining the path strings? i.e. instead of AbTesting.js having `var _default = (0, _createIcon["default"])('M4 2A2 2 0 0 0 2 4V12H4V8H6V12H8V4A2 2 0 0 0 6 2H4M4 4H6V6H4M22 15.5V14A2 2 0 0 0 20 12H16V22H20A2 2 0 0 0 22 20V18.5A1.54 1.54 0 0 0 20.5 17A1.54 1.54 0 0 0 22 15.5M20 20H18V18H20V20M20 16H18V14H20M5.79 21.61L4.21 20.39L18.21 2.39L19.79 3.61Z');` that line would be `var _default = (0, _createIcon["default"])(mdiAbIcon);`.

This would deduplicate the icon path string in case someone is using mdi-material-ui but also depending on something that depends on `@mdi/js`; if that's a thing.

Although I suppose this would break mdi-material-ui's support for environments that do not support tree-shaking since mdi-material-ui does not support direct imports.

**Comment by leMaik** [comment]
> Although I suppose this would break mdi-material-ui's support for environments that do not support tree-shaking since mdi-material-ui does not support direct imports.

Exactly, that's why I considered but then dropped it. What do you mean with direct imports?

**Comment by dantman** [comment]
> What do you mean with direct imports?

Sorry, I meant `@mdi/js` does not support direct imports of individual paths as separate files.

**Comment by leMaik** [comment]
Exactly, and that forces tree-shaking support. Not a problem because most people use Webpack or Rollup, but still. This package uses a similar approach to Material-UI's way to bundle the original Material Icons.

**Comment by leMaik** [comment]
The specific icons you asked for will be available after updating to mdi [4.4.95](https://cdn.materialdesignicons.com/4.4.95/), which is not released yet.
I'll keep this issue open until then.
