### ISSUE TITLE
Missing half Dice icons

### ISSUE THREAD

**Issue by cncolder** [TeamWertarbyte/mdi-material-ui#26]
https://unpkg.com/mdi-material-ui@6.5.0/index.js

https://materialdesignicons.com/icon/dice-d10

**Comment by cncolder** [comment]
And another dice

Dice1Outline
Dice2Outline
Dice3Outline
Dice4Outline
Dice5Outline
Dice6Outline
DiceD10
DiceD12
DiceD20
DiceD4
DiceD6
DiceD8
DiceMultipleOutline

**Comment by leMaik** [comment]
It's up to date but some icons from the mdi homepage are not released yet. See my comment in #25.

**Comment by leMaik** [comment]
These icons will be available after updating to mdi [4.4.95](https://cdn.materialdesignicons.com/4.4.95/), which is not released yet.
