### ISSUE TITLE
circular dependeny issue after upgrade v6.13.1

### ISSUE THREAD

**Issue by dohomi** [TeamWertarbyte/mdi-material-ui#30]
Hi
after upgrade `6.13.0 => 6.13.1`  and I receive following issue while using this package:
```
[ warn ]  ./node_modules/mdi-material-ui/TextBox.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
```
Downgrade to `6.13.0` solved it for now

**Comment by duongdev** [comment]
This happens because of the `index.es.js` is importing `TextBox.js` but the file name actually is `Textbox.js`

**Comment by leMaik** [comment]
@duongdev Thanks for finding out what's wrong here! :clap: Should we add a special case and name that single file `Text-box.js` but still export it as `TextBox` from `index.js`?

**Comment by duongdev** [comment]
@leMaik yeah, I think that solution is OK. Or we just keep all js files name the same as the icons' name from materialdesignicon.com (kebab-cased) to prevent similar issues later?

**Comment by leMaik** [comment]
@duongdev That would break all imports for people who don't use tree shaking to import from the `index.js` :grimacing:

**Comment by xs9627** [comment]
Got the same error. Hope it could been fixed soon. Thanks.

**Comment by duongdev** [comment]
@leMaik ahh I see, so I think your solution is the best for now 👍

**Comment by leMaik** [comment]
Updated all three versions and also added checks so this doesn't happen again.
