### ISSUE TITLE
Version 5.24.1 "material-ui" instead of "@material-ui/core"

### ISSUE THREAD

**Issue by mceIdo** [TeamWertarbyte/mdi-material-ui#31]
Version 5.24.1 uses `material-ui/SvgIcon` in src/util/createIcon.js, instead of `@material-ui/core/SvgIcon`
Seems like this version was published from the "legacy" branch instead of "v5" for some reason.

**Comment by leMaik** [comment]
Maybe it's time to stop maintaining three versions in parallel.

**Comment by mceIdo** [comment]
yeah I actually took the opportunity to upgrade, but still, thought you might want to know :)

**Comment by leMaik** [comment]
@mceIdo It's fixed in v5.24.2. There are projects that take a lot of time to update (including projects for MUI v3 that I maintain). But after two years without releases, maybe it's time to let at least v4 (for Material-UI 0.x) go.
