### ISSUE TITLE
I am using "mdi-material-ui": "^6.10.0" version and cannot find cube-off mdi icon there although

### ISSUE THREAD

**Issue by jhrabows** [TeamWertarbyte/mdi-material-ui#32]

**Comment by jhrabows** [comment]
I am using "mdi-material-ui": "^6.10.0" version and cannot find cube-off mdi icon.
Other variants of cube icon are there. I tried to update version of the dependency but getting an error
```
npm install mdi-material-ui@6.12.0
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file
```

**Comment by jhrabows** [comment]
not sure why it got closed

**Comment by leMaik** [comment]
Please try the latest version, 6.1.14. The error you got looks like a download error or npm related error, can't do much about that.

**Comment by jhrabows** [comment]
Hi leMaik,
I am getting the same -5 error with version 6.14.0. Something must have changed after 6.10.0 because 6.10.0 and earlier versions do not have this issue. Just by looking at the error I am guessing that this is related to compression format which my version of npm does not understand. I am using npm v 6.4.1.  Can you confirm that you can use 6.14.0 as a dependency in your package.json and the version of npm you use?

**Comment by leMaik** [comment]
They may have renamed the icon. I can't say why npm doesn't work on your computer. Make sure you are using the latest version of npm.

If this icon is new, it should be included in the latest release.

**Comment by leMaik** [comment]
The cube-off icon is now there and I can install the package on my machine, so I'm closing this.

@jhrabows I'm sorry I couldn't help you with the npm issue. The [npm community](https://npm.community/) might be a better place to get help. :-)
