### ISSUE TITLE
Your site is unusable

### ISSUE THREAD

**Issue by manualva7** [TeamWertarbyte/mdi-material-ui#33]
Just like the title says. You're loading all icons at once and it makes my browser go haywire. I have to wait 30 seconds for the site to load.
![mdi-website](https://user-images.githubusercontent.com/41272874/82162557-3b719700-985a-11ea-82af-432c3f75cce8.png)

**Comment by leMaik** [comment]
Indeed, but there's nothing we can do about that. We're only wrapping the icons for Material-UI, the site is made by the MDI team.
