### ISSUE TITLE
Image is not a constructor

### ISSUE THREAD

**Issue by masbaehr** [TeamWertarbyte/mdi-material-ui#34]
Unfortunately there seems to be a collision with 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

Is there a solution to fix this when importing Image?

**Comment by leMaik** [comment]
`import { Image as ImageIcon } from "mdi-material-ui"`?

**Comment by masbaehr** [comment]
Ah okay thanks :) Maybe a small info about this could be useful in the readme  👍

**Comment by leMaik** [comment]
@masbaehr If you want, you can submit a PR that adds a small note to the readme. I hope that people will find it when searching the issues, though.
