### ISSUE TITLE
CamelCase generator issue

### ISSUE THREAD

**Issue by YuriGor** [TeamWertarbyte/mdi-material-ui#39]
Hi, thank you for maintaining this stuff :)
There are some icon names with a single character wrapped by dashes, e.g. `alpha-t-box-outline`
So in @mdi/js it's correctly converted to [mdiAlphaTBoxOutline](https://materialdesignicons.com/icon/alpha-t-box-outline)
But in our case we have lower "b" in "Box": `AlphaTboxOutline`

**Comment by leMaik** [comment]
Thanks for reporting this. Now that we use `@mdi/js` we can just drop the ~camel~ pascal case generator step because the icon names are already in PascalCase.

I'll fix this in the next releases.

**Comment by YuriGor** [comment]
🥳
