### ISSUE TITLE
TrayArrowDown is missing?

### ISSUE THREAD

**Issue by ZYinMD** [TeamWertarbyte/mdi-material-ui#40]
I found `tray-arrow-down` on https://materialdesignicons.com, but it seems not exported by this package?

**Comment by leMaik** [comment]
Somehow it's also missing in `@mdi/js` so nothing we can fix here… Please report this at materialdesignicons.

**Comment by ZYinMD** [comment]
I see https://github.com/Templarian/MaterialDesign does include `tray-arrow-down.svg`, so where's the correct place to report the issue? Which is the first upstream repo that missed this icon?

**Comment by leMaik** [comment]
@mdi/js doesn't include it. Just report it at the repo you linked. Maybe they just didn't release a new version yet.
