### ISSUE TITLE
material-ui dependence

### ISSUE THREAD

**Issue by badri1991** [TeamWertarbyte/mdi-material-ui#43]
i've updated material ui to **5.0.0-rc.1** and package name has been changed form @material-ui to @mui 
but mdi has been used @material-ui in their dependence

i have this error
_ERROR in ../../node_modules/mdi-material-ui/util/createIcon.js 12:13-47
Module not found: Error: Can't resolve '@material-ui/core/utils' in '/Documents/frontend-core/node_modules/mdi-material-ui/util'_

**Comment by ShotSkydiver** [comment]
I made a PR to fix this here: [https://github.com/TeamWertarbyte/mdi-material-ui/pull/42](https://github.com/TeamWertarbyte/mdi-material-ui/pull/42) and there's a temporary NPM package link in that PR that you can install until it's merged!

**Comment by henry-young** [comment]
Bump as MUIv5 is now officially released

**Comment by 662** [comment]
+1

**Comment by dylancrockett** [comment]
+1

**Comment by leMaik** [comment]
Fixed in v7.0.1 and v7.1.0 (same but with latest Material Design Icons).
