### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by sandrosc** [TeamWertarbyte/mdi-material-ui#44]
We recently decided to not use software that is licensed with WTFPL, Unlicense or CC0 anymore (see [1] or [2] for some problems with these licenses).

Since we would like to keep using `mdi-material-ui` it would be great if you could relicense this package under the MIT license. Or is there a specific reason for you to keep using the WTFPL?

[1] https://en.wikipedia.org/wiki/WTFPL#Reception
[2] https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

**Comment by leMaik** [comment]
As clearly stated in the license, you can do whatever the f_ck you want with this code. Just copy it and relicense it or whatever. :smile: Keep in mind that the icons are MIT.

**Comment by leMaik** [comment]
Keep in mind that the README says:

> The scripts included in this repository are licensed under the WTFPL. The icons are licensed under the MIT license (see Material Design Icons and the NOTICE file).

So as long as you're using the icons and not the scripts to generate the files, it's all MIT. :wink:

**Comment by leMaik** [comment]
Edit edit: The next versions will be MIT. :man_shrugging:

**Comment by sandrosc** [comment]
Thank you very much xD.

BTW, I personally like the WTFPL, we just can't use it unfortunately.
