### ISSUE TITLE
TruckSnowflake icon is not exported

### ISSUE THREAD

**Issue by dzes483** [TeamWertarbyte/mdi-material-ui#45]
The [TruckSnowflake](https://github.com/Templarian/MaterialDesign/issues/6221) icon was released in version [6.5.95](https://github.com/Templarian/MaterialDesign/milestone/59?closed=1) of MaterialDesign, but it is missing from mdi-material-ui. It is also included in [@mdi/js](https://github.com/Templarian/MaterialDesign-JS/blob/master/commonjs/mdi.d.ts).

**Comment by leMaik** [comment]
Thanks for the reminder. :+1: 

I updated everything and v6.5.95 of Material Design Icons is included in mdi-material-ui v5.35.0, v6.24.0 and v7.2.0 (pick the correct one for the MUI version you're using).
