### ISSUE TITLE
WizardHat is not exported

### ISSUE THREAD

**Issue by Forfold** [TeamWertarbyte/mdi-material-ui#46]
I see `WizardHat` available on `@mdi/js`, but it is not available in `mdi-material-ui` which is the package we've been using for a while now.

**Comment by leMaik** [comment]
Thanks for the reminder. :+1: 

I updated everything and v6.5.95 of Material Design Icons is included in mdi-material-ui v5.35.0, v6.24.0 and v7.2.0 (pick the correct one for the MUI version you're using).

**Comment by Forfold** [comment]
Thanks!!
