### ISSUE TITLE
Re-release with @mdi/js version v6.6.96

### ISSUE THREAD

**Issue by schlosser** [TeamWertarbyte/mdi-material-ui#47]
We'd love to use some of the icons that have been added recently!

**Comment by leMaik** [comment]
Thanks for the reminder! I should automate this process with github actions... Ideally with a trigger from mdi/js

**Comment by schlosser** [comment]
Bumping this, did the release go through?

**Comment by schlosser** [comment]
Hey @leMaik – sorry to keep poking, but would you mind triggering another release?

**Comment by leMaik** [comment]
Thanks for the reminder. Done in v5.36.0, v6.25.0 and v7.3.0 :ship:

**Comment by schlosser** [comment]
Thank you!
