### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by MazeChaZer** [TeamWertarbyte/mdi-material-ui#5]
It would be awesome if the TypeScript definitions for all the icons could be generated, too 🌟

**Comment by leMaik** [comment]
Good idea! Generate ALL the files! :tada:

**Comment by leMaik** [comment]
I'll publish this later…

**Comment by MazeChaZer** [comment]
Great, thanks for the quick implementation 👍

**Comment by leMaik** [comment]
@MazeChaZer "I'll publish this later". :sweat: Well, it's published now. Would you mind testing if the typings are fine?

**Comment by MazeChaZer** [comment]
Thanks :+1:
I'm currently on vacation, I will test this not later than 09.01.

**Comment by MazeChaZer** [comment]
@leMaik Works great, thank you 👍
