### ISSUE TITLE
All icons rerender without any change

### ISSUE THREAD

**Issue by oulfr** [TeamWertarbyte/mdi-material-ui#51]
example of icons:

`<AccountOutline sx={{mr: 2}}/>`

![image](https://user-images.githubusercontent.com/35069360/188263202-02c2bcf6-9d44-4156-b426-847e86a282e9.png)

**Comment by oulfr** [comment]
same behavior with mui icons

**Comment by leMaik** [comment]
That's what react does when putting new objects into props (eg. sx) every time. 🙁
