### ISSUE TITLE
Update Request (for newer icons)

### ISSUE THREAD

**Issue by jesselee-ambrook** [TeamWertarbyte/mdi-material-ui#52]
Hey maintainers!

I was looking through the icon set, and saw a certain one I need isn't available because it's fairly new. (https://materialdesignicons.com/icon/storefront-plus-outline). It's available in the latest version of MaterialDesign-SVG (7.0.96) (https://github.com/Templarian/MaterialDesign-SVG/blob/v7.0.96/svg/storefront-plus-outline.svg)

Could you update to this version? Happy to do a PR if that's what you prefer

**Comment by leMaik** [comment]
Hi, will do.
