### ISSUE TITLE
Update to MDI v7.2.96

### ISSUE THREAD

**Issue by jhil** [TeamWertarbyte/mdi-material-ui#54]
Hey there! Would a maintainer mind updating this library to MDI v7.2.96 from v7.0.96 (https://www.npmjs.com/package/@mdi/js?activeTab=versions)? Let me know if you'd prefer I submit a PR, thanks so much!

**Comment by leMaik** [comment]
Done :heavy_check_mark:

**Comment by jhil** [comment]
Thanks so much, @leMaik !
