### ISSUE TITLE
@mui/joy

### ISSUE THREAD

**Issue by alcaroff** [TeamWertarbyte/mdi-material-ui#55]
Hello, is a support planned for the new @mui/joy
https://mui.com/joy-ui/guides/using-icon-libraries/ ?

**Comment by leMaik** [comment]
That should just work with the latest version. I'm using joy in a spare time project and I'll verify it soon.

**Comment by leMaik** [comment]
This already works. Just like @mui/icons-material, this has a @mui/material peer dependency (we need the `SvgIcon` component too) and then you can use the icons everywhere.
