### ISSUE TITLE
Update to MDI v7.4.47

### ISSUE THREAD

**Issue by jhil** [TeamWertarbyte/mdi-material-ui#57]
A new version of MDI was just released! Can someone help upgrade this library's version?

Here's the code changes from the last bump (by @leMaik) : https://github.com/TeamWertarbyte/mdi-material-ui/commit/9f91f19c4bdae0365a09aea34c7b9e4b3a153d45

**Comment by leMaik** [comment]
Will do asap

**Comment by jhil** [comment]
I just realized that the GitHub repo isn't updated even though the website is. Should probably wait a few days after all until the next build.

**Comment by leMaik** [comment]
Fixed via versions 5.42.0, 6.30.0 and 7.8.0. Please update to the version that corresponds to your MUI version and have a happy new year. :tada:
