### ISSUE TITLE
MUI 6 Support

### ISSUE THREAD

**Issue by joncursi** [TeamWertarbyte/mdi-material-ui#58]
This library is fully compatible with MUI 6, but the peer dependencies have a restriction that only allow MUI 5 to be installed. Can we open up the peer deps to support `5.x || 6.x`?

https://mui.com/blog/material-ui-v6-is-out/

**Comment by leMaik** [comment]
The peer dependency is updated in v7.9.2 :+1:

**Comment by joncursi** [comment]
Awesome, thank you!
