### ISSUE TITLE
Icon not found

### ISSUE THREAD

**Issue by KevinAsher** [TeamWertarbyte/mdi-material-ui#6]
Hi, first of all thanks for providing this lib. The package probably needs a little update with the icons website, I can't import [this](https://materialdesignicons.com/icon/arrow-expand-horizontal) icon, and probably others are missing too.

**Comment by leMaik** [comment]
@KevinAsher Thanks for reporting this issue. It's an upstream issue, so I forwarded it. :+1:

**Comment by PeterShaggyNoble** [comment]
That icon will be available in the next release of Material Design Icons.

**Comment by leMaik** [comment]
@PeterShaggyNoble Great! :+1: @KevinAsher This package will be updated as soon as the next MDI release is available.

**Comment by KevinAsher** [comment]
@leMaik, @PeterShaggyNoble thank you for the fast feedback!
