### ISSUE TITLE
Update webpack to v3

### ISSUE THREAD

**Issue by davejm** [TeamWertarbyte/mdi-material-ui#7]
Hi, it'd be great if you could update the webpack dependency to v3 as I've had some issues when installing this module along-side others in a create-react-app template.

**Comment by leMaik** [comment]
:open_mouth: It's only a dev dependency, we could remove it entirely. :+1:

**Comment by davejm** [comment]
Hmm that's what I thought, except I think there's a problem with npm package resolution that causes webpack builds to complain if there are different versions of webpack in transient dependencies (I would have thought devDeps wouldn't matter though). Basically I got this issue after installing this package https://github.com/facebook/create-react-app/issues/4076

**Comment by davejm** [comment]
I deleted node_modules, used yarn instead of npm to install packages again and it started up fine.

**Comment by leMaik** [comment]
:man_shrugging:

**Comment by leMaik** [comment]
@davejm The actual package that is _generated_ by this module has no dependencies, though. Are you sure that this package caused the issues?
