### ISSUE TITLE
Incompatible with material-ui v1 

### ISSUE THREAD

**Issue by leonardiwagner** [TeamWertarbyte/mdi-material-ui#8]
When building my react app with weback, for every icon inside this package is thrown that error:
```
ERROR in ./node_modules/mdi-material-ui/ViewDay.js
Module not found: Error: Can't resolve 'material-ui/SvgIcon' in '/MY_PROJECT_FOLDER/node_modules/mdi-material-ui'
 @ ./node_modules/mdi-material-ui/ViewDay.js 11:15-45
 @ ./node_modules/mdi-material-ui/index.es.js
 @ ./src/components/Menu/MenuContainer.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/index.js
```
I'm using webpack 3, npm 5, and material-ui@next (1.0.0-beta.40)

**Comment by leonardiwagner** [comment]
I think the problem is about using material-ui 1.0, with 0.20 builds fine. Any plans to be compatible with the newer version?

**Comment by leonardiwagner** [comment]
For those with the same problem, I started to use [mdi-react](https://github.com/levrik/mdi-react) lib instead and works fine with v1.

I did not spend time studying how could fix the problem but maybe using the required lib as dependency rather than relying on material-ui could be safer.

**Comment by leMaik** [comment]
@leonardiwagner I'm using it with material-ui 1.0.0 and it works perfectly fine. `SvgIcon` is [still available](https://github.com/mui-org/material-ui/tree/v1-beta/src/SvgIcon) in material-ui 1.0.0 as well as 0.x, I don't know why your webpack config doesn't work.

Without any more information, I can't help you, though.

**Comment by owtham** [comment]
@material-ui/icons have a peer dependency of @material-ui/core. @orenkudev answer helped me.
